package com.customer.user.request.model;

import java.util.Date;
import java.util.Optional;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
@DynamoDBTable(tableName = "CustomerRequests")
public class CustomerRequests2 {
	private Integer requestId;
	private String requestTitle;
	private String requestCategory;
	private String requestStatus;
	private String customerEmail;
	private String requestDescription;
	private Date requestDate;
	
	 @DynamoDBHashKey
	    @DynamoDBAutoGeneratedKey
	public Integer getRequestId() {
		return requestId;
	}
	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}
	 @DynamoDBAttribute
	public String getRequestTitle() {
		return requestTitle;
	}
	public void setRequestTitle(String requestTitle) {
		this.requestTitle = requestTitle;
	}
	 @DynamoDBAttribute
	public String getRequestCategory() {
		return requestCategory;
	}
	public void setRequestCategory(String requestCategory) {
		this.requestCategory = requestCategory;
	}
	 @DynamoDBAttribute
	public String getRequestStatus() {
		return requestStatus;
	}
	 @DynamoDBAttribute
	public void setRequestStatus(String requestStatus) {
		this.requestStatus = requestStatus;
	}
	 @DynamoDBAttribute
	public String getCustomerEmail() {
		return customerEmail;
	}
	 
	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}
	 @DynamoDBAttribute
	public String getRequestDescription() {
		return requestDescription;
	}
	public void setRequestDescription(String requestDescription) {
		this.requestDescription = requestDescription;
	}
	 @DynamoDBAttribute
	public Date getRequestDate() {
		return requestDate;
	}
	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}
	public CustomerRequests2(Integer requestId, String requestTitle, String requestCategory, String requestStatus,
			String customerEmail, String requestDescription, Date requestDate) {
		super();
		this.requestId = requestId;
		this.requestTitle = requestTitle;
		this.requestCategory = requestCategory;
		this.requestStatus = requestStatus;
		this.customerEmail = customerEmail;
		this.requestDescription = requestDescription;
		this.requestDate = requestDate;
	}
	public CustomerRequests2() {
		super();
	}
	


   
}